services:
  - type: web
    name: bike-rental-api
    runtime: docker
    repo: https://github.com/JenkaBY/bike-rental
    branch: render-deploy
    dockerfilePath: ./service/Dockerfile
    dockerContext: .
    envVars:
      - key: DATASOURCE_URL
        fromDatabase:
          name: bike-rental-db
          property: connectionString
      - key: DATASOURCE_USER
        fromDatabase:
          name: bike-rental-db
          property: user
      - key: DATASOURCE_SECRET
        fromDatabase:
          name: bike-rental-db
          property: password

databases:
  - name: bike-rental-db
    databaseName: bikerental
    plan: free
