server.port=8081
spring.config.import=optional:nocommit.properties

DATASOURCE_URL=jdbc:postgresql://localhost:5432/bikerental
CORS_ALLOWED_ORIGINS=http://localhost:4200,http://localhost:4201,http://localhost:4202,https://jenkaby.github.io
OAUTH2_ISSUER=http://localhost:8080
ADMIN_SPA_CLIENT_ID=bike-rental-admin
ADMIN_SPA_REDIRECT_URIS=http://localhost:4201/login/callback
ADMIN_SPA_POST_LOGOUT_URIS=http://localhost:4201
OPERATOR_SPA_CLIENT_ID=bike-rental-operator
OPERATOR_SPA_REDIRECT_URIS=http://localhost:4202/login/callback
OPERATOR_SPA_POST_LOGOUT_URIS=http://localhost:4202
BOOTSTRAP_ENABLED=true
BOOTSTRAP_ADMIN_USERNAME=admin
BOOTSTRAP_ADMIN_EMAIL=admin@bike-rental.local
# Logging
LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
JWT_PRIVATE_KEY_LOCATION=classpath:keys/bike-rental-identity/jwt-local-private.pem
JWT_PUBLIC_KEY_LOCATION=classpath:keys/bike-rental-identity/jwt-local-public.pem