management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: ${app.cors.allowed-origins}
        allowed-methods: ${app.cors.allowed-methods}
        allowed-headers: ${app.cors.allowed-headers}
        allow-credentials: ${app.cors.allow-credentials}
        max-age: ${app.cors.max-age}
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true