spring:
  application:
    name: bike-rental
  config:
    import: application-management-config.yaml
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_SECRET}
  liquibase:
    analytics-enabled: false
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    enabled: true
    urls-primary-name: all
  api-docs:
    enabled: true

app:
  default-locale: en
  customers:
    search-limit-result: 10
  rental:
    time-increment: 5m
    forgiveness:
      overtime-duration: 7m
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600